language: java
jdk: oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: heroku
  api_key:
    secure: im31fLYympTu4fWyyNXPgTS0xAoYPaNVP7oK7xvrz6DTdDFTYrJyWfB69fXedo/RM3ZPkVQBIntDnqycQ2BaqaLaVqVr2FG0Je4dczwXmdsx681cgkuXo/wwy/lfN2cBYPzz/f4YH6pE6+7FScp4pJRn9WnSyWfh2L8goA0VL+4tvX0/q/VdV0CLUKYNr5I71MSQjc94lazMibYvJoNoyUuhpL1HMU/HlFH2sukJo3T0UWA7f7KGuOobzEidvo5A3fefdKTPFpbIUdKjRwMsbUSiirmTfl9vXdmPFtOf580HSHRq3IcyP0E9eciGcy3ybwEn7eMfqcKhiRzSPwvb5DDKAAdDXMum2cbV1GtL6FIoq0YjJxBv7bXfH6YfU2t0S0hb25eY997BB1ZZ2S0i2NRg/l5fWdX4pFhr2CzvszPN75AEAKmqsNMgPpxmwtDI0hP8ixb2gRJpdOELWvpfLpQhvG5IZko423IXCbqpXixSYrLaMxAvTvikFRMCsumIiFWM2+g2ffoufju/pEwtVY/VJcXSCgd91t3uq4wNohW9jYiKRnI+UYdWjjQeGZCf4NX8r4Jzsgzj/Ao5ZBMjBV98DUFI/QdCyGyhyvD6V8FraUdcAEwSLHJPmnlK7x3MfP9bZE65o0pykSkjPtFyHpikiU/HSAt089mHwcnpTvU=
  app: fisystem
  on:
    repo: contortion777/FISystem
